// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}

void ui_destroy( void )
{ui_Screen1_screen_destroy();
}

#define MANEUVER_IMAGE_COUNT 67

const lv_img_dsc_t* maneuverImages[MANEUVER_IMAGE_COUNT] = {
    &ui_img_ic_depart_png,
    &ui_img_ic_depart_png,
    &ui_img_ic_destination_png,
    &ui_img_ic_destination_left_png,
    &ui_img_ic_destination_right_png,
    &ui_img_ic_straight_png,
    &ui_img_ic_turn_left_png,
    &ui_img_ic_turn_right_png,
    &ui_img_ic_fork_left_png,
    &ui_img_ic_fork_right_png,
    &ui_img_ic_turn_slight_left_png,
    &ui_img_ic_turn_slight_right_png,
    &ui_img_ic_turn_sharp_left_png,
    &ui_img_ic_turn_sharp_right_png,
    &ui_img_ic_turn_u_turn_clockwise_png,
    &ui_img_ic_turn_u_turn_counterclockwise_png,
    &ui_img_ic_merge_png,
    &ui_img_ic_merge_left_png,
    &ui_img_ic_merge_right_png,
    &ui_img_ic_fork_left_png,
    &ui_img_ic_fork_right_png,
    &ui_img_ic_straight_png,
    &ui_img_ic_turn_left_png,
    &ui_img_ic_turn_right_png,
    &ui_img_ic_fork_left_png,
    &ui_img_ic_fork_right_png,
    &ui_img_ic_turn_slight_left_png,
    &ui_img_ic_turn_slight_right_png,
    &ui_img_ic_turn_sharp_left_png,
    &ui_img_ic_turn_sharp_right_png,
    &ui_img_ic_turn_u_turn_clockwise_png,
    &ui_img_ic_turn_u_turn_counterclockwise_png,
    &ui_img_ic_straight_png,
    &ui_img_ic_merge_left_png,
    &ui_img_ic_merge_right_png,
    &ui_img_ic_fork_left_png,
    &ui_img_ic_fork_right_png,
    &ui_img_ic_turn_slight_left_png,
    &ui_img_ic_turn_slight_right_png,
    &ui_img_ic_turn_sharp_left_png,
    &ui_img_ic_turn_sharp_right_png,
    &ui_img_ic_turn_u_turn_clockwise_png,
    &ui_img_ic_turn_u_turn_counterclockwise_png,
    &ui_img_ic_roundabout_clockwise_png,
    &ui_img_ic_roundabout_counterclockwise_png,
    &ui_img_ic_roundabout_straight_clockwise_png,
    &ui_img_ic_roundabout_straight_counterclockwise_png,
    &ui_img_ic_roundabout_left_clockwise_png,
    &ui_img_ic_roundabout_left_counterclockwise_png,
    &ui_img_ic_roundabout_right_clockwise_png,
    &ui_img_ic_roundabout_right_counterclockwise_png,
    &ui_img_ic_roundabout_slight_left_clockwise_png,
    &ui_img_ic_roundabout_slight_left_counterclockwise_png,
    &ui_img_ic_roundabout_slight_right_clockwise_png,
    &ui_img_ic_roundabout_slight_right_counterclockwise_png,
    &ui_img_ic_roundabout_sharp_left_clockwise_png,
    &ui_img_ic_roundabout_sharp_left_counterclockwise_png,
    &ui_img_ic_roundabout_sharp_right_clockwise_png,
    &ui_img_ic_roundabout_sharp_right_counterclockwise_png,
    &ui_img_ic_roundabout_u_turn_clockwise_png,
    &ui_img_ic_roundabout_u_turn_counterclockwise_png,
    &ui_img_ic_roundabout_exit_clockwise_png,
    &ui_img_ic_roundabout_exit_counterclockwise_png,
    &ui_img_ic_ferry_boat_png,
    &ui_img_ic_ferry_train_png,
    &ui_img_ic_straight_png
};
