// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_MainTab;
extern lv_obj_t *ui_Navigation;
extern lv_obj_t *ui_NavDirection;
extern lv_obj_t *ui_ETA;
extern lv_obj_t *ui_Instruction;
extern lv_obj_t *ui_EKM;
// NEW COMPONENTS
extern lv_obj_t *ui_Clock;
extern lv_obj_t *ui_Speed;
extern lv_obj_t *ui_Header;
extern lv_obj_t *ui_SpeedUnit;
extern lv_obj_t *ui_ClockContainer;
extern lv_obj_t *ui_NavCard;
extern lv_obj_t *ui_CallPanel;
extern lv_obj_t *ui_CallerName;
extern lv_obj_t *ui_CallAccept;
extern lv_obj_t *ui_CallDecline;
// CUSTOM VARIABLES
extern lv_obj_t *uic_NavDirection;
extern lv_obj_t *uic_ETA;
extern lv_obj_t *uic_Instruction;
extern lv_obj_t *uic_EKM;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

