// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_EKM;
lv_obj_t *uic_Instruction;
lv_obj_t *uic_ETA;
lv_obj_t *uic_NavDirection;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_MainTab = NULL;lv_obj_t *ui_Navigation = NULL;lv_obj_t *ui_NavDirection = NULL;lv_obj_t *ui_ETA = NULL;lv_obj_t *ui_Instruction = NULL;lv_obj_t *ui_EKM = NULL;
lv_obj_t *ui_Clock = NULL;
lv_obj_t *ui_Speed = NULL;
lv_obj_t *ui_Header = NULL;
lv_obj_t *ui_SpeedUnit = NULL;
lv_obj_t *ui_ClockContainer = NULL;
lv_obj_t *ui_NavCard = NULL;
lv_obj_t *ui_CallPanel = NULL;
lv_obj_t *ui_CallerName = NULL;
lv_obj_t *ui_CallAccept = NULL;
lv_obj_t *ui_CallDecline = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    // Navigation Card Container
    ui_NavCard = lv_obj_create(ui_Screen1);
    lv_obj_set_size(ui_NavCard, 320, 400); // Space below header
    lv_obj_set_x(ui_NavCard, 0);
    lv_obj_set_y(ui_NavCard, 80); // Start after 80px header
    lv_obj_set_align(ui_NavCard, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_NavCard, lv_color_hex(0xF0F0F0), 0); // Light Background
    lv_obj_set_style_radius(ui_NavCard, 0, 0);
    lv_obj_set_style_border_width(ui_NavCard, 0, 0);
    lv_obj_clear_flag(ui_NavCard, LV_OBJ_FLAG_SCROLLABLE);

    // Floating Inner Card for Navigation info
    lv_obj_t * ui_NavInnerCard = lv_obj_create(ui_NavCard);
    lv_obj_set_size(ui_NavInnerCard, 300, 340);
    lv_obj_set_align(ui_NavInnerCard, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_NavInnerCard, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_radius(ui_NavInnerCard, 24, 0);
    lv_obj_set_style_border_width(ui_NavInnerCard, 2, 0);
    lv_obj_set_style_border_color(ui_NavInnerCard, lv_color_hex(0xCCCCCC), 0);
    lv_obj_clear_flag(ui_NavInnerCard, LV_OBJ_FLAG_SCROLLABLE);

    ui_NavDirection = lv_img_create(ui_NavInnerCard);
    lv_img_set_src(ui_NavDirection, &ui_img_ic_depart_png);
    lv_obj_set_width(ui_NavDirection, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_NavDirection, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_NavDirection, LV_ALIGN_TOP_MID);
    lv_obj_set_y(ui_NavDirection, 10);
    lv_img_set_zoom(ui_NavDirection, 300);
    
    ui_EKM = lv_label_create(ui_NavInnerCard);
    lv_obj_set_align(ui_EKM, LV_ALIGN_TOP_MID);
    lv_obj_set_y(ui_EKM, 130);
    lv_label_set_text(ui_EKM, "00m");
    lv_obj_set_style_text_color(ui_EKM, lv_color_hex(0x007AFF), 0);
    lv_obj_set_style_text_font(ui_EKM, &lv_font_montserrat_32, 0);

    ui_Instruction = lv_label_create(ui_NavInnerCard);
    lv_obj_set_width(ui_Instruction, lv_pct(90));
    lv_obj_set_height(ui_Instruction, 80);
    lv_obj_set_align(ui_Instruction, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_Instruction, 60);
    lv_label_set_text(ui_Instruction, "Navigation Not Started Yet");
    lv_obj_set_style_text_color(ui_Instruction, lv_color_hex(0x000000), 0);
    lv_obj_set_style_text_align(ui_Instruction, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_text_font(ui_Instruction, &lv_font_montserrat_20, 0);

    ui_ETA = lv_label_create(ui_NavInnerCard);
    lv_obj_set_align(ui_ETA, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_ETA, -15);
    lv_label_set_text(ui_ETA, "00min");
    lv_obj_set_style_text_color(ui_ETA, lv_color_hex(0x555555), 0);
    lv_obj_set_style_text_font(ui_ETA, &lv_font_montserrat_16, 0);

    // --- Dashboard Header ---
    ui_Header = lv_obj_create(ui_Screen1);
    lv_obj_set_size(ui_Header, 320, 80); // INCREASED height
    lv_obj_set_align(ui_Header, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_Header, lv_color_hex(0xFFFFFF), 0); // WHITE Header
    lv_obj_set_style_bg_opa(ui_Header, 255, 0);
    lv_obj_set_style_border_width(ui_Header, 1, 0);
    lv_obj_set_style_border_side(ui_Header, LV_BORDER_SIDE_BOTTOM, 0);
    lv_obj_set_style_border_color(ui_Header, lv_color_hex(0xDDDDDD), 0);
    lv_obj_set_style_radius(ui_Header, 0, 0);
    lv_obj_clear_flag(ui_Header, LV_OBJ_FLAG_SCROLLABLE);

    // Speedometer
    ui_Speed = lv_label_create(ui_Header);
    lv_obj_set_align(ui_Speed, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Speed, 15);
    lv_obj_set_y(ui_Speed, -8);
    lv_label_set_text(ui_Speed, "0");
    lv_obj_set_style_text_font(ui_Speed, &lv_font_montserrat_40, 0); // LARGER FONT
    lv_obj_set_style_text_color(ui_Speed, lv_color_hex(0x007AFF), 0); // Sport Blue

    ui_SpeedUnit = lv_label_create(ui_Header);
    lv_obj_set_align(ui_SpeedUnit, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_SpeedUnit, 15);
    lv_obj_set_y(ui_SpeedUnit, 22);
    lv_label_set_text(ui_SpeedUnit, "km/h");
    lv_obj_set_style_text_font(ui_SpeedUnit, &lv_font_montserrat_14, 0);
    lv_obj_set_style_text_color(ui_SpeedUnit, lv_color_hex(0x666666), 0);

    // Clock Pill
    ui_ClockContainer = lv_obj_create(ui_Header);
    lv_obj_set_size(ui_ClockContainer, 100, 40); // LARGER Clock section
    lv_obj_set_align(ui_ClockContainer, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_ClockContainer, -10);
    lv_obj_set_style_bg_color(ui_ClockContainer, lv_color_hex(0xEEEEEE), 0);
    lv_obj_set_style_radius(ui_ClockContainer, 20, 0);
    lv_obj_set_style_border_width(ui_ClockContainer, 1, 0);
    lv_obj_set_style_border_color(ui_ClockContainer, lv_color_hex(0xCCCCCC), 0);
    lv_obj_clear_flag(ui_ClockContainer, LV_OBJ_FLAG_SCROLLABLE);

    ui_Clock = lv_label_create(ui_ClockContainer);
    lv_obj_set_align(ui_Clock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Clock, "00:00");
    lv_obj_set_style_text_font(ui_Clock, &lv_font_montserrat_20, 0); // LARGER Clock text
    lv_obj_set_style_text_color(ui_Clock, lv_color_hex(0x007AFF), 0); // Sport Blue

    // --- NEW: Call Overlay ---
    ui_CallPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_size(ui_CallPanel, 320, 480);
    lv_obj_set_align(ui_CallPanel, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_CallPanel, lv_color_hex(0x000000), 0);
    lv_obj_set_style_bg_opa(ui_CallPanel, 245, 0);
    lv_obj_add_flag(ui_CallPanel, LV_OBJ_FLAG_HIDDEN); // Hidden by default

    lv_obj_t * call_header = lv_label_create(ui_CallPanel);
    lv_obj_set_align(call_header, LV_ALIGN_TOP_MID);
    lv_obj_set_y(call_header, 60);
    lv_label_set_text(call_header, "INCOMING CALL");
    lv_obj_set_style_text_font(call_header, &lv_font_montserrat_14, 0);
    lv_obj_set_style_text_color(call_header, lv_color_hex(0xAAAAAA), 0);

    ui_CallerName = lv_label_create(ui_CallPanel);
    lv_obj_set_align(ui_CallerName, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_CallerName, -20);
    lv_label_set_text(ui_CallerName, "Unknown Caller");
    lv_obj_set_style_text_font(ui_CallerName, &lv_font_montserrat_28, 0);
    lv_obj_set_style_text_color(ui_CallerName, lv_color_hex(0x007AFF), 0); // Sport Blue Name

    ui_CallAccept = lv_btn_create(ui_CallPanel);
    lv_obj_set_size(ui_CallAccept, 120, 60);
    lv_obj_set_align(ui_CallAccept, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_x(ui_CallAccept, 15);
    lv_obj_set_y(ui_CallAccept, -80);
    lv_obj_set_style_bg_color(ui_CallAccept, lv_color_hex(0x28C76F), 0); // Modern Green
    lv_obj_set_style_radius(ui_CallAccept, 30, 0);
    
    lv_obj_t *accept_label = lv_label_create(ui_CallAccept);
    lv_label_set_text(accept_label, "ACCEPT");
    lv_obj_set_align(accept_label, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(accept_label, &lv_font_montserrat_14, 0);

    ui_CallDecline = lv_btn_create(ui_CallPanel);
    lv_obj_set_size(ui_CallDecline, 120, 60);
    lv_obj_set_align(ui_CallDecline, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_x(ui_CallDecline, -15);
    lv_obj_set_y(ui_CallDecline, -80);
    lv_obj_set_style_bg_color(ui_CallDecline, lv_color_hex(0xEA5455), 0); // Modern Red
    lv_obj_set_style_radius(ui_CallDecline, 30, 0);
    
    lv_obj_t *decline_label = lv_label_create(ui_CallDecline);
    lv_label_set_text(decline_label, "DECLINE");
    lv_obj_set_align(decline_label, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(decline_label, &lv_font_montserrat_14, 0);

    uic_NavDirection = ui_NavDirection;
    uic_ETA = ui_ETA;
    uic_Instruction = ui_Instruction;
    uic_EKM = ui_EKM;
}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_MainTab= NULL;
ui_Navigation= NULL;
uic_NavDirection= NULL;
ui_NavDirection= NULL;
uic_ETA= NULL;
ui_ETA= NULL;
uic_Instruction= NULL;
ui_Instruction= NULL;
uic_EKM= NULL;
ui_EKM= NULL;
ui_Clock= NULL;
ui_Speed= NULL;
ui_Header= NULL;
ui_SpeedUnit= NULL;
ui_ClockContainer= NULL;
ui_NavCard= NULL;
ui_CallPanel= NULL;
ui_CallerName= NULL;
ui_CallAccept= NULL;
ui_CallDecline= NULL;

}
